# Based on the Gerhut's great work
# https://github.com/Gerhut/Gerhut/tree/master/.github/workflows

name: updateReadme

on:
  schedule:
    - cron:  '*/10 * * * *'
      
jobs:
  covid-stats:
    name: Covid stats
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: covidstats
    - uses: actions/setup-node@v1
    - run: yarn --frozen-lockfile
    - id: run
      run: |
        NEWREADME="$(yarn --silent start)"
        NEWREADME="${NEWREADME//'%'/'%25'}"
        NEWREADME="${NEWREADME//$'\n'/'%0A'}"
        NEWREADME="${NEWREADME//$'\r'/'%0D'}"
        echo "::set-output name=newreadme::$NEWREADME"
    outputs:
      newreadme: ${{ steps.run.outputs.newreadme }}

  update:
    needs:
    - covid-stats
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - run: |
        cat <<'EOF' | tee README.md
        ${{ needs.covid-stats.outputs.newreadme }}
        EOF
    - id: changed
      run: git diff --exit-code
      continue-on-error: true
    - if: ${{ steps.changed.outcome == 'failure' }}
      run: |
        git add README.md
        git config --local user.name "GitHub Action"
        git config --local user.email action@github.com
        git commit --message 'Update README.md'
    - if: ${{ steps.changed.outcome == 'failure' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
